# Generated by Django 3.2.16 on 2024-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('syntax', models.CharField(max_length=255, verbose_name='Синтаксис команды')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('-id',),
                'default_related_name': 'commands',
            },
        ),
    ]
