# Generated by Django 3.2.16 on 2024-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_auto_20240910_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('-id',),
                'default_related_name': 'tags',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='commands', to='command.Tag', verbose_name='Тег'),
        ),
    ]
