# Generated by Django 3.2.16 on 2024-09-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_auto_20240910_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='tag',
            new_name='tags',
        ),
    ]
