# Generated by Django 3.2.16 on 2024-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_rename_tag_command_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Идентификатор'),
        ),
    ]
