# Generated by Django 3.2.16 on 2024-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='image',
            field=models.ImageField(blank=True, upload_to='command_images', verbose_name='Изображение'),
        ),
    ]
