# Generated by Django 4.2.16 on 2024-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_alter_command_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='tags',
            field=models.ManyToManyField(blank=True, to='command.tag', verbose_name='Тег'),
        ),
    ]
